// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/AliyunContainerService/ack-secret-manager/cli/pkg/apis/alibabacloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExternalSecrets implements ExternalSecretInterface
type FakeExternalSecrets struct {
	Fake *FakeAlibabacloudV1alpha1
	ns   string
}

var externalsecretsResource = v1alpha1.SchemeGroupVersion.WithResource("externalsecrets")

var externalsecretsKind = v1alpha1.SchemeGroupVersion.WithKind("ExternalSecret")

// Get takes name of the externalSecret, and returns the corresponding externalSecret object, and an error if there is any.
func (c *FakeExternalSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ExternalSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externalsecretsResource, c.ns, name), &v1alpha1.ExternalSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalSecret), err
}

// List takes label and field selectors, and returns the list of ExternalSecrets that match those selectors.
func (c *FakeExternalSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExternalSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externalsecretsResource, externalsecretsKind, c.ns, opts), &v1alpha1.ExternalSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExternalSecretList{ListMeta: obj.(*v1alpha1.ExternalSecretList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExternalSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalSecrets.
func (c *FakeExternalSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externalsecretsResource, c.ns, opts))

}

// Create takes the representation of a externalSecret and creates it.  Returns the server's representation of the externalSecret, and an error, if there is any.
func (c *FakeExternalSecrets) Create(ctx context.Context, externalSecret *v1alpha1.ExternalSecret, opts v1.CreateOptions) (result *v1alpha1.ExternalSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externalsecretsResource, c.ns, externalSecret), &v1alpha1.ExternalSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalSecret), err
}

// Update takes the representation of a externalSecret and updates it. Returns the server's representation of the externalSecret, and an error, if there is any.
func (c *FakeExternalSecrets) Update(ctx context.Context, externalSecret *v1alpha1.ExternalSecret, opts v1.UpdateOptions) (result *v1alpha1.ExternalSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externalsecretsResource, c.ns, externalSecret), &v1alpha1.ExternalSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalSecret), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExternalSecrets) UpdateStatus(ctx context.Context, externalSecret *v1alpha1.ExternalSecret, opts v1.UpdateOptions) (*v1alpha1.ExternalSecret, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(externalsecretsResource, "status", c.ns, externalSecret), &v1alpha1.ExternalSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalSecret), err
}

// Delete takes name of the externalSecret and deletes it. Returns an error if one occurs.
func (c *FakeExternalSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(externalsecretsResource, c.ns, name, opts), &v1alpha1.ExternalSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externalsecretsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExternalSecretList{})
	return err
}

// Patch applies the patch and returns the patched externalSecret.
func (c *FakeExternalSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ExternalSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externalsecretsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ExternalSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalSecret), err
}
