// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ExternalSecretListerExpansion allows custom methods to be added to
// ExternalSecretLister.
type ExternalSecretListerExpansion interface{}

// ExternalSecretNamespaceListerExpansion allows custom methods to be added to
// ExternalSecretNamespaceLister.
type ExternalSecretNamespaceListerExpansion interface{}

// SecretStoreListerExpansion allows custom methods to be added to
// SecretStoreLister.
type SecretStoreListerExpansion interface{}

// SecretStoreNamespaceListerExpansion allows custom methods to be added to
// SecretStoreNamespaceLister.
type SecretStoreNamespaceListerExpansion interface{}
