kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ack-secret-manager
subjects:
- kind: ServiceAccount
  name: ack-secret-manager
roleRef:
  kind: Role
  name: ack-secret-manager
  apiGroup: rbac.authorization.k8s.io
