// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/AliyunContainerService/ack-secret-manager/cli/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ExternalSecrets returns a ExternalSecretInformer.
	ExternalSecrets() ExternalSecretInformer
	// SecretStores returns a SecretStoreInformer.
	SecretStores() SecretStoreInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ExternalSecrets returns a ExternalSecretInformer.
func (v *version) ExternalSecrets() ExternalSecretInformer {
	return &externalSecretInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SecretStores returns a SecretStoreInformer.
func (v *version) SecretStores() SecretStoreInformer {
	return &secretStoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
