// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/AliyunContainerService/ack-secret-manager/ack-secret-manager-cli/pkg/apis/alibabacloud/v1alpha1"
	scheme "github.com/AliyunContainerService/ack-secret-manager/ack-secret-manager-cli/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretStoresGetter has a method to return a SecretStoreInterface.
// A group's client should implement this interface.
type SecretStoresGetter interface {
	SecretStores(namespace string) SecretStoreInterface
}

// SecretStoreInterface has methods to work with SecretStore resources.
type SecretStoreInterface interface {
	Create(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.CreateOptions) (*v1alpha1.SecretStore, error)
	Update(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.UpdateOptions) (*v1alpha1.SecretStore, error)
	UpdateStatus(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.UpdateOptions) (*v1alpha1.SecretStore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SecretStore, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SecretStoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretStore, err error)
	SecretStoreExpansion
}

// secretStores implements SecretStoreInterface
type secretStores struct {
	client rest.Interface
	ns     string
}

// newSecretStores returns a SecretStores
func newSecretStores(c *AlibabacloudV1alpha1Client, namespace string) *secretStores {
	return &secretStores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretStore, and returns the corresponding secretStore object, and an error if there is any.
func (c *secretStores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretStore, err error) {
	result = &v1alpha1.SecretStore{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretstores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretStores that match those selectors.
func (c *secretStores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretStoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretStoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretstores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretStores.
func (c *secretStores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretstores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretStore and creates it.  Returns the server's representation of the secretStore, and an error, if there is any.
func (c *secretStores) Create(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.CreateOptions) (result *v1alpha1.SecretStore, err error) {
	result = &v1alpha1.SecretStore{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretstores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretStore).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretStore and updates it. Returns the server's representation of the secretStore, and an error, if there is any.
func (c *secretStores) Update(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.UpdateOptions) (result *v1alpha1.SecretStore, err error) {
	result = &v1alpha1.SecretStore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretstores").
		Name(secretStore.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretStore).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *secretStores) UpdateStatus(ctx context.Context, secretStore *v1alpha1.SecretStore, opts v1.UpdateOptions) (result *v1alpha1.SecretStore, err error) {
	result = &v1alpha1.SecretStore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretstores").
		Name(secretStore.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretStore).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretStore and deletes it. Returns an error if one occurs.
func (c *secretStores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretstores").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretStores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretstores").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretStore.
func (c *secretStores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretStore, err error) {
	result = &v1alpha1.SecretStore{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretstores").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
