// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	alibabacloudv1alpha1 "github.com/AliyunContainerService/ack-secret-manager/cli/pkg/apis/alibabacloud/v1alpha1"
	versioned "github.com/AliyunContainerService/ack-secret-manager/cli/pkg/client/clientset/versioned"
	internalinterfaces "github.com/AliyunContainerService/ack-secret-manager/cli/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/AliyunContainerService/ack-secret-manager/cli/pkg/client/listers/alibabacloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SecretStoreInformer provides access to a shared informer and lister for
// SecretStores.
type SecretStoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SecretStoreLister
}

type secretStoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecretStoreInformer constructs a new informer for SecretStore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecretStoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecretStoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecretStoreInformer constructs a new informer for SecretStore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecretStoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AlibabacloudV1alpha1().SecretStores(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AlibabacloudV1alpha1().SecretStores(namespace).Watch(context.TODO(), options)
			},
		},
		&alibabacloudv1alpha1.SecretStore{},
		resyncPeriod,
		indexers,
	)
}

func (f *secretStoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecretStoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *secretStoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alibabacloudv1alpha1.SecretStore{}, f.defaultInformer)
}

func (f *secretStoreInformer) Lister() v1alpha1.SecretStoreLister {
	return v1alpha1.NewSecretStoreLister(f.Informer().GetIndexer())
}
