name: Test

on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.0
        check-latest: true
        cache: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.11.4
        args: --verbose --timeout=10m
  go-security-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -exclude-dir=pkg/apis ./...'

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.0
      env:
        GOPATH: ${{ env.HOME }}

    - name: Build
      run: make build