name: Test

on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
        check-latest: true
        cache: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
        args: --verbose
  Gosec:
    name: Run Gosec Security Scanner
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
      env:
        GOPATH: ${{ env.HOME }}

    - name: Build
      run: make build

    - name: Test
      run: make test